source 'https://cdn.cocoapods.org'
platform :ios, '13.0'
use_frameworks! :linkage => :static
inhibit_all_warnings!

target 'iosApp' do
  pod 'composeApp', :path => '../composeApp'

  pod 'FirebaseCore', '>= 10.0'
  pod 'FirebaseAuth', '>= 10.0'
  pod 'GoogleSignIn', '>= 7.0'
end
