source 'https://cdn.cocoapods.org'

platform :ios, '16.0'
use_frameworks! :linkage => :static
inhibit_all_warnings!

target 'iosApp' do
    pod 'ComposeApp', :path => '../composeApp'
      pod 'Firebase/Auth'
      pod 'Firebase/Core'
end