source 'https://cdn.cocoapods.org'

platform :ios, '16.0'
inhibit_all_warnings!

target 'iosApp' do
    use_frameworks!
    pod 'ComposeApp', :path => '../composeApp'
    pod 'Firebase/Auth'
    pod 'Firebase/Core'
    pod 'GoogleSignIn'
end

post_install do |installer|
  ignored_targets = ['KotlinGradlePlugin', 'composeApp']

  installer.pods_project.targets.each do |target|
    next if ignored_targets.include?(target.name)

    puts "✅ Patching deployment target for: #{target.name}"

    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.3'
    end
  end
end